### ISSUE TITLE
Change Snack title & maybe reference by sourceUrl

### ISSUE THREAD

**Issue by brentvatne** [tokkozhin/react-native-neomorph-shadows#1]
It seems like there is a bug with Snack when loading projects with the `|` character - so "Clock | Shadows and Neomorphism" doesn't load in the in-browser preview. It would be good to change the title to "Clock - Shadows and Neomorphism"

Alternatively, you can embed the source in your GitHub repo and link to it using the `sourceUrl` param, eg: here is a URL for Snack that points to a gist I made with your same example code: https://snack.expo.io/?sourceUrl=https%3A%2F%2Fgist.githubusercontent.com%2Fbrentvatne%2F0ea48e9de9a256b8129349117a686e1b%2Fraw%2Faac22adeb0a8316dd586ee97dc675e0cb5c81bf4%2Fexample.js&dependencies=react-native-reanimated%2Cexpo-constants%2Creact-native-neomorph-shadows%2Creact-native-svg&name=Clock+-+Shadows+and+Neomorphism

You can generate the URL like this:

```js
let queryString = new URLSearchParams({
  sourceUrl: 'https://gist.githubusercontent.com/brentvatne/0ea48e9de9a256b8129349117a686e1b/raw/aac22adeb0a8316dd586ee97dc675e0cb5c81bf4/example.js', // your url here
  dependencies: ['react-native-reanimated', 'expo-constants', 'react-native-neomorph-shadows', 'react-native-svg'],
  name: 'Clock - Shadows and Neomorphism',
}).toString();
let url = `https://snack.expo.io?` + queryString;
```

This makes it easier to keep up to date because if you point it to something in your repository you can just update it as you update your code, rather than having to remember to go to Snack.

**Comment by tokkozhin** [comment]
Thanks for that! Name changed.
