### ISSUE TITLE
The new version 1.0.1 is not valid for Expo?

### ISSUE THREAD

**Issue by georgeMorales** [tokkozhin/react-native-neomorph-shadows#10]
I have updated to the new version 1.0.1 and installed @ react-native-community/art and I get an error
Error while updating property 'stroke in shadow node on type: ARTShape
Expo SDK 37

**Comment by tokkozhin** [comment]
Yes, rn ART lib was recently deprecated from expo and therefore unfortunately can no longer be used with expo.
