### ISSUE TITLE
When using prop "inner" to NeoMorph Component Error while updating property 'stroke' in shadow node of type: ARTShape 

### ISSUE THREAD

**Issue by mukulramchandani** [tokkozhin/react-native-neomorph-shadows#13]
Updated react-native-neomorph-shadows to latest version today and updated the code as well (NeomorphBox to Neomorph) but facing this issue since that. Tried few things nothing's working.
I'm version expo 36.

`import React from 'react';
import { StyleSheet, Text, View , Image , TextInput ,Picker,TouchableOpacity ,ActivityIndicator,Dimensions} from 'react-native';
import {useFonts} from '@use-expo/font';
import { useNavigation } from '@react-navigation/native';

import { Neomorph ,Shadow } from 'react-native-neomorph-shadows';

import { KeyboardAwareScrollView } from 'react-native-keyboard-aware-scroll-view';

export default function SignUp1() {
    const [value, onChangeText] = React.useState('');
    const [cityValue, onChangeCity] = React.useState('');
    const [selectedValue, setSelectedValue] = React.useState("country");
    const [mob, onChangeMob] = React.useState('');
    const [fontLoaded] = useFonts({'Kelly-Slab':require('./assets/fonts/KellySlab-Regular.ttf'),
    'Lato-Bold':require('./assets/fonts/Lato-Bold.ttf'),
    'Lato-Regular':require('./assets/fonts/Lato-Regular.ttf')
  });

    const navigation = useNavigation();

    if(!fontLoaded)
    return (
      <View style={{flex:1,justifyContent:'center',backgroundColor: '#31343C',}}>
    <ActivityIndicator size='large' color="#fff"/></View>
      )
      else
  return (
    <View style={styles.container}>
    <KeyboardAwareScrollView 
    style={{ backgroundColor: '#31343C' }}
      resetScrollToCoords={{ x: 0, y: 0 }}
      //contentContainerStyle={styles.container}
      scrollEnabled={true}
      showsVerticalScrollIndicator = {false}
    
    >
      <View style={{
          marginTop:30
      }}>
    
      <Image
      style={{
          width:200,
          height:200,
          alignSelf:'center'
      }}
      source={
       require('/home/rgeet13/Desktop/mukul/p/proto/assets/icon1.png')
      }    />
      <Text style={{
          alignSelf:'center',
          fontSize:25,
          fontFamily:'Kelly-Slab',
          color:'#fff'
      }}>||  ||</Text>

      
      <Neomorph
     
      useArt
      inner

          style={{
            width: 150,
            height: 150,
            justifyContent: 'center',
            alignItems: 'center',
            borderRadius: 20,
            shadowRadius: 20,
            backgroundColor: '#ffffff',
          }}
        >
        
        </Neomorph>`

Any ideas how can I resolve this ?  

![ss](https://user-images.githubusercontent.com/16251020/80282857-59534c80-8731-11ea-9704-442bfc4fda95.jpeg)

**Comment by tokkozhin** [comment]
Latest expo version supporting ART is 35

**Comment by mukulramchandani** [comment]
Thanks for the reply. :) How can I use this library in expo version 36 or I have to downgrade it to 35 only ? If yes , Can please give me some link/info for how to downgrade to 35 ? 
This is great library indeed :) Thx.

**Comment by tokkozhin** [comment]
@mukulramchandani Yes, you can downgrade to v35, but I can’t help you because don’t use expo or you can use it in bare rn project. So, google for help)

**Comment by shimangdian** [comment]
Hello！If i don't use expo, how can i fix this?

**Comment by tokkozhin** [comment]
@shimangdian when you get this error?

**Comment by shimangdian** [comment]
@tokkozhin yes , because of this error, I don't use this library at present. I want to use it to make my APP more beautiful
