### ISSUE TITLE
Invariant Violation: View config not found for name ARTShape.

### ISSUE THREAD

**Issue by IceTeddy** [tokkozhin/react-native-neomorph-shadows#19]
![Simulator Screen Shot - iPhone 11 - 2020-05-13 at 17 17 23](https://user-images.githubusercontent.com/1934749/81794825-f25dd200-953d-11ea-8d77-7f8ad2c6b97e.png)

**Comment by tokkozhin** [comment]
Hi, If you use expo, see 
Duplicate of #10
