### ISSUE TITLE
How can I animate colors?

### ISSUE THREAD

**Issue by fr3fou** [tokkozhin/react-native-neomorph-shadows#2]
I'm trying to make a pulsing animation, but i keep getting this error:
![image](https://user-images.githubusercontent.com/1344906/74691951-b42a6e00-51ed-11ea-8541-2f6d32864c0f.png)
```js
const AnimatedNeomorphBox = Animated.createAnimatedComponent(NeomorphBox)
```

**Comment by tokkozhin** [comment]
Unfortunately, the shadows do not support animation yet.

**Comment by fr3fou** [comment]
i don't need to animate the shadows, i want to animate the backgroundColor D:

**Comment by tokkozhin** [comment]
Misunderstood) Will be fixed in the next release.

**Comment by sagarrs** [comment]
hi i want to add liner gradient to NeomorphBox how to do it ?
