### ISSUE TITLE
How to add one sided borderRadius ?

### ISSUE THREAD

**Issue by wahaj-47** [tokkozhin/react-native-neomorph-shadows#22]
I was able to add borderRadiusTopStart, borderRadiusTopEnd, borderRadiusBottomStart and borderRadiusBottomEnd properties on iOS, but on Android they only work if the inner prop is set to true. How might I add it to Android also ?

**Comment by tokkozhin** [comment]
These props are not supported yet.

**Comment by wahaj-47** [comment]
I actually managed to add iOS support and limited support for Android in my fork. 
Only tested the Neomorph component, not sure if it works with the rest.
