### ISSUE TITLE
Support aspectRatio

### ISSUE THREAD

**Issue by MoKhajavi75** [tokkozhin/react-native-neomorph-shadows#26]
Hey

I want to have some circles so I use `aspectRatio` but it has no effect!

Any tricks or it can be added via a PR?

**Comment by tokkozhin** [comment]
Yes, currently you can't use this prop with Shadow, Neomorph components. But now you can try it with new experimental **ShadowFlex**, **NeomorphFlex**, which support all View styles. More info in README.
