### ISSUE TITLE
How can i change the shadow width?

### ISSUE THREAD

**Issue by gang544043963** [tokkozhin/react-native-neomorph-shadows#3]
This is really an amazing component.

The shadow is too large(wide) for me, how can i make the shadow smaller(thinner)?

Thank you!

**Comment by tokkozhin** [comment]
Hi! This component is designed to copy the work of native ios shadows. This means that only shadowRadius in style can control the thickness of the shadow.

**Comment by tokkozhin** [comment]
Hi! This component is designed to copy the work of native ios shadows. This means that only shadowRadius in style can control the thickness of the shadow.

**Comment by gang544043963** [comment]
I believe this component's shadow is wider than iOS. It will be better if you could adapt this!
