### ISSUE TITLE
Nested Neomorph example errors out

### ISSUE THREAD

**Issue by Schwefelhexa** [tokkozhin/react-native-neomorph-shadows#39]
When I run the [Nested Neomorph](https://github.com/tokkozhin/react-native-neomorph-shadows#nested-neomorph) example with Expo 38 on Android, I get the following error:

```
Error while updating property 'stroke' in shadow node of type: ARTShape
java.lang.String cannot be cast to abi38_0_0.com.facebook.react.bridge.ReadableArray
```

This immediately crashes Expo.

**Comment by tokkozhin** [comment]
duplicate https://github.com/tokkozhin/react-native-neomorph-shadows/issues/13#issuecomment-619402241
