### ISSUE TITLE
ART is becoming deprecated. Move to react-native-svg?

### ISSUE THREAD

**Issue by Ashniu123** [tokkozhin/react-native-neomorph-shadows#44]
Hi,

From this [issue](https://github.com/react-native-art/art/issues/75) on ART's repo, it is being deprecated due to legacy code and maintainance crap (which is affecting this repo).

They suggest moving to [react-native-svg](https://github.com/react-native-svg/react-native-svg).

**Comment by tokkozhin** [comment]
@Ashniu123 Hi, yes, I agree with you, and I used [react-native-svg](https://github.com/react-native-svg/react-native-svg) before for shadows, but performance was less then with library ART and I had to change it.
And as I said before, this is a temporary solution until someone writes a native solution.
