### ISSUE TITLE
Library closed and broke my app

### ISSUE THREAD

**Issue by elmaedesistemas** [tokkozhin/react-native-neomorph-shadows#45]
Hi!
I need use this library for apply some shadow in some components, but when i import the library, suddenly the app is closed, I need help please, I put down my versions of react and react native

"react": "16.13.1",
"react-native": "0.63.4",

PD: sorry for my bad English. <3

**Comment by tokkozhin** [comment]
@coffescript  Hi! Yes it may be caused by https://github.com/facebook/react-native/issues/29633#issuecomment-694187116
You can install this temporary: https://github.com/tokkozhin/art Instead of https://github.com/react-native-art/art

**Comment by elmaedesistemas** [comment]
hello!
i have another question, how can i install your version of react native art?
i talk about the command, for install the react native art of facebook, i use yarn add @react-native-community/art
but for install your version? how can i do?

Thanks!

**Comment by KarthikKnot1** [comment]
yarn add https://github.com/tokkozhin/art.git

That's what I did, that should work.

**Comment by KarthikKnot1** [comment]
> @coffescript Hi! Yes it may be caused by [facebook/react-native#29633 (comment)](https://github.com/facebook/react-native/issues/29633#issuecomment-694187116)
> You can install this temporary: https://github.com/tokkozhin/art Instead of https://github.com/react-native-art/art

This worked for me! Thanks :)

**Comment by elmaedesistemas** [comment]
Thats works, i close this issue, thanks!!!
