### ISSUE TITLE
Reason why this was switched to react-native-art?

### ISSUE THREAD

**Issue by yolpsoftware** [tokkozhin/react-native-neomorph-shadows#47]
What was the exact reason why this was built with react-native-art when release 1.0.0 was created? What was used before release 1.0.0?

We need to use this library on Expo, and Expo suggests using react-native-svg instead of react-native-art.

Maybe we will create a version using react-native-svg instead of react-native-art.

**Comment by Ashniu123** [comment]
I had raised a similar issue here #44 
Hope this addresses your concern.

**Comment by yolpsoftware** [comment]
@Ashniu123 I see, thanks!

**Comment by Ashniu123** [comment]
Close issue please?
