### ISSUE TITLE
Can we use Neomorph Box in Touchable Opacity?

### ISSUE THREAD

**Issue by vedant-dobby** [tokkozhin/react-native-neomorph-shadows#5]
I want to use this in touchable opacity or for buttons? Can you guys tell me how to that and retain the styling required?

**Comment by tokkozhin** [comment]
It's not quite clear what you mean.
You can do this:
```
<TouchableOpacity>
  <NeomorphBox/>
</TouchableOpacity>
```
:smirk:

**Comment by vedant-dobby** [comment]
Okay thanks
