### ISSUE TITLE
single corner border radius borderBottomRightRadius 

### ISSUE THREAD

**Issue by hkrhasan** [tokkozhin/react-native-neomorph-shadows#52]
if i give borderBottomRightRadius it's not working

**Comment by pierpo** [comment]
I can confirm that I'm having the same issue: only `borderRadius` works, not the corner values like `borderTopRightRadius`.

(thanks for the awesome lib by the way :tada: )

**Comment by osamality** [comment]
I'm also facing this issue

**Comment by pierpo** [comment]
I did a PR with the fix @osamality , it's not merged but you can take the patch 😊 

https://github.com/tokkozhin/react-native-neomorph-shadows/issues/52

**Comment by hkrhasan** [comment]
> I did a PR with the fix @osamality , it's not merged but you can take the patch 😊
> 
> #52

thanks
